### ISSUE TITLE
Newly created playlists aren’t functional or permanent; tracks then disappear if they can be added at all

### ISSUE THREAD

**Issue by slobulike** [riverscuomo/public-bug-hunt#7] opened 2023-09-06 21:08 UTC
**Describe the bug**

If I make a playlist then try to add a track to it, the playlist I made appears on the screen but isn't selectable, and if I choose "new playlist" the message shows that a new playlist was created but then that doesn't seem to get created.

**To Reproduce**
1. Go to 'Player screen'
2. Click on '3 dots next to any track the user has access to'
3. Select 'Add to other playlist'
4. Click on any playlist
5. Click on New Playlist 

**Expected behavior**
The track is successfully added to the selected playlist.
Or, the new playlist is created and the track is added.

**Screenshots**
![image](https://github.com/riverscuomo/public-bug-hunt/assets/48949712/11413a51-d5fc-4c46-8d28-a406549d933f)

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 13
 - Browser: Android App
 - Version: 1.8.7 (165)

**Comment by riverscuomo** [comment] 2023-09-06 21:11
@slobulike do you remember if this feature ever worked on mobile?

**Comment by slobulike** [comment] 2023-09-06 21:29
> @slobulike do you remember if this feature ever worked on mobile?

I'm not totally certain I'm afraid, but I think it probably did because I have quite a lot of playlists and I very rarely use a desktop so feel like I would have made them on mobile.

However, the counter to that is that if you create a new playlist you have included a message saying "No tracks in playlist. Add tracks on a large screen device". So maybe I just made them on an iPad.

**Comment by riverscuomo** [comment] 2023-09-06 21:43
I created that fallback message recently.
I haven't been able to find any code related to creating playlists on small
screens.
Thanks for the report Anyway. I'm sure many people will have the same
question.
It does seem like a useful feature. I'm just wondering if I should classify
it in my mind as a bug fix or an enhancement.

**Comment by riverscuomo** [comment] 2023-09-17 01:59
should be fixed in build 171

created a new weezifyplayerbloc event to select track for adding to playlists

**Comment by Mel01000001** [comment] 2023-09-23 12:22
This worked for me, but the songs eventually disappeared from the playlist, usually after closing and reopening the app.  The screenshots show adding several songs to a playlist, followed by the playlist being left with one remaining song (which wasn't one of the ones added).

Device: Samsung Galaxy S23+
OS: Android 13
Browser: Android App
Version: 1.9.0 (173)

![Screenshot_20230923_184642](https://github.com/riverscuomo/public-bug-hunt/assets/144282154/94bd2892-8110-44d2-a24f-273bf10cf066)

![Screenshot_20230923_184618](https://github.com/riverscuomo/public-bug-hunt/assets/144282154/a4af6fc0-2046-47a9-a1dd-7fd56304b497)

**Comment by SlightlyCompletely** [comment] 2023-09-26 19:55
Issue exists on in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1: I can click the plus button to create a playlist, and the new (empty) playlist will open up, but it seems to not exist if I navigate away and look for it.

**Comment by The-King-Tom** [comment] 2023-09-26 22:30
Updated to Android 1.9.1 (build 175). 

If I try to create a new playlist, it opens a new playlist, but like @SlightlyCompletely noted, the new playlist will disappear if I navigate away.

Additionally, if I add it to an existing playlist, it will show up in the new playlist. However, after exiting and reopening the app, the newly added song will be missing from the playlist.

**Comment by SlightlyCompletely** [comment] 2023-09-27 17:41
Issue remains on iPad Air (running iPadOS 17.0.1) in Weezify v1.9.2 (176). Playlists appear to be created but there’s no way to add tracks on iPad and playlists disappear after navigating away to different section of Weezify, another app, or closing the app.
Video shows playlist being created and ability to open it, but playlists aren’t persistent.


https://github.com/riverscuomo/public-bug-hunt/assets/144279871/8d51f9cc-5c08-4948-8df1-455ad300be1f

**Comment by riverscuomo** [comment] 2023-10-22 17:47
Click on overflow 3 dots on track > Add to New Playlist

seems to add it to New Releases

![image](https://github.com/riverscuomo/public-bug-hunt/assets/24362267/30555a61-f766-4ecb-a5d5-bc3fa66aea14)

**Comment by SlightlyCompletely** [comment] 2023-10-23 17:25
> Click on overflow 3 dots on track > Add to New Playlist
> 
> 
> 
> seems to add it to New Releases
> 
> 
> 
> ![image](https://github.com/riverscuomo/public-bug-hunt/assets/24362267/30555a61-f766-4ecb-a5d5-bc3fa66aea14)
> 
> 

This is precisely what's happening on iPad (Air 5th gen running iPadOS 17.0.3) in Weezify 1.10.0 (179).

**Comment by KCreek1** [comment] 2023-10-23 21:12
Those are the same two tracks I see on new releases before I even try to add to a new playlist.

iPhone SE 2nd gen
iOS 17.0.3
Weezify ios 1.10.0 (179)

 ![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/9e77b391-a8e2-4778-8ff1-22a5a2ca83fa)

**Comment by riverscuomo** [comment] 2023-10-27 16:33
SmallAddToPlaylistScreen

it was adding an non-existent bloc event CreatePlaylistWithTrack

i switched it to CreatePlaylist and just had it add state.TrackToAdd

**Comment by KCreek1** [comment] 2023-10-29 21:39
Able to create playlists and add songs. 

iPhone SE 2nd gen
iOS 17.0.3
iOS app 185 (1.11.0)

**Comment by KCreek1** [comment] 2023-11-03 20:58
I can create a playlist and add songs but if I close app and reopen - they lead to "page not available."

iPhone SE 2nd gen
iOS 17.0.3
Weezify iOS v186 (1.12.0)



https://github.com/riverscuomo/public-bug-hunt/assets/144278926/bc5b4ba9-c569-466e-b58c-c465078d1e62

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/4d064c7c-48b9-4281-89ad-6fd0a86ae760

**Comment by SlightlyCompletely** [comment] 2023-11-04 00:13
> I can create a playlist and add songs but if I close app and reopen - they lead to "page not available."
> 
> iPhone SE 2nd gen iOS 17.0.3 Weezify iOS v186 (1.12.0)

Same experience on iPad Air 5th gen running iPadOS 17.0.3 and Weezify 1.12.0 (186).

**Comment by SlightlyCompletely** [comment] 2023-12-01 02:21
Sporadically an issue on iPad, but subsequent logout/logins were inconsistent about which playlists were shown, both for newly created user and my older primary account. My account created for testing purposes today seemed more consistently to work properly.

Device: iPad Air 5th gen
OS: iPadOS 17.1.1
Weezify 1.13.0 (188)

**Comment by KCreek1** [comment] 2023-12-01 04:39
> Same as before: I can create playlists. And I can add songs to both existing and new playlist using overflow menu. But once I close app and reopen - they're gone from the library and their icons in my profile produce page not available messages. 
> 
> iPhone SE (2nd gen)
> iOS 17.2.1
> Weezify ios 188 (1.13.0)



 Addendum to my comment:

I reopened the app after a couple hours and the two playlists I created previously were in library and could be played. I closed the app and reopened and they're gone again.

**Comment by The-King-Tom** [comment] 2023-12-13 02:50
On Android (build 189), searched for a song, hit the three overflow dots, added the song to an existing playlist. Logged out, logged back in, song is showing at the end of the playlist. Closed Weezify, re-opened, song is showing at the end of the playlist. Opened playlist on Weezify Chrome (for Android), song is showing at the end of the playlist.

Device: Pixel 5a
OS: Android V 14
Weezify: 189 (1.13.1)

**Comment by The-King-Tom** [comment] 2023-12-13 02:51
Adding to a new playlist passes, but the new playlist doesn't always show up. On Android (build 189), searched for a song, hit the three overflow dots, added the song to a new playlist. 

The new playlist did not show up, so I logged out and restarted Weezify. Then the new playlist with the added song showed up.

Device: Pixel 5a
OS: Android V 14
Weezify: 189 (1.13.1)

**Comment by KCreek1** [comment] 2023-12-16 18:25
Created playlists seem to be functioning normally now on iPhone and iPad with v192 (13.1.1)

**Comment by Mel01000001** [comment] 2023-12-19 00:52
Adding to created and existing playlists functioning on Android build 192 (13.1.2), but unable to scroll to access all pre-existing playlists.

**Comment by riverscuomo** [comment] 2024-01-31 14:06
@Mel01000001 @KCreek1 I'm not able to reproduce this error. Could it simply be that you don't have any playlists to add the track to?

**Comment by Mel01000001** [comment] 2024-01-31 18:24
I've attached a screen recording.  It worked one time, but all other tests
do this.

**Comment by KCreek1** [comment] 2024-04-16 01:53
Playlists functioning correctly on iPhone in weezify ios 215 (1.17.2) .

**Comment by KCreek1** [comment] 2024-09-26 02:45
Seems to be functioning normally on iOS and android.

**Closed by KCreek1** 2024-09-26 02:45 UTC
Labels: iOS, android, fixed in upcoming release, P3-Medium
